more parliament permissions
aol/moloch pull request #2224
Opened 2023-03-28 15:32 UTC by 31453

hide login button if not a parliament user
hide edit parliament button if not a parliament admin show cluster/group errors fixed on the bottom for visibility

fixes #2118

2023-03-28 15:38 UTC, awick requested changes

2023-03-28 15:38 UTC, awick commented on parliament/parliament.js
> -  if (!ArkimeUtil.isString(req.body.commonAuth)) {
should still check if it is !== undefined?

2023-03-28 16:49 UTC, 31453 commented on parliament/vueapp/src/components/Settings.vue
> +                The HTTP Realm for user authentication. Set this to the same realm as your Akime clusters to share credentials. By default "Moloch" if not set.
@awick Want to help me with this text. It sounds awkward to me 🤷

2023-03-29 20:45 UTC, awick commented on tests/parliament.t
> +ok($result->{success});
Can you add ```viewerGet("/regressionTests/deleteAllUsers");``` to end

2023-03-29 20:47 UTC, awick commented on tests/parliament.t
> +# parliament user cannot access/udpate settings/parliament
would be nice if at least some of these tested against the text ;)

2023-03-30 14:11 UTC, merged